---
- name: install httpd
  hosts: localhost
  tasks:
    - name: install latest version
      yum:
        name: httpd
        state: latest
    - name: running state
      service:
        name: httpd
        state: started
